CREATE TABLE IF NOT EXISTS public.carro (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    modelo character varying(250),
    fabricante character varying(250),
    ano_fabricacao integer NOT NULL,
    ano_modelo integer NOT NULL,
    CONSTRAINT carro_pkey PRIMARY KEY (id)
);

INSERT INTO public.carro(
	modelo, fabricante, ano_fabricacao, ano_modelo)
	VALUES ('Gol', 'Volks', 2022, 2023);